Expose more Details of Purl and Cpe for writing
CycloneDX/cyclonedx-rust-cargo pull request #381
Opened 2023-03-23 13:55 UTC by koa

2023-08-26 18:00 UTC, lfrancke commented
Hi,
would you mind adding your sign off/DCO as per these instructions?

https://github.com/CycloneDX/cyclonedx-rust-cargo/runs/12224035251

Thank you

2023-10-27 18:55 UTC, Shnatsel requested changes
Needs one change, other than that looks good. Thanks!

2023-10-27 18:55 UTC, Shnatsel commented on cyclonedx-bom/src/external_models/uri.rs
> +impl<'a> From<PackageUrl<'a>> for Purl {
The PackageUrl crate currently has version 0.3.0, not 1.0 or something like that. It is likely that they will bump the version frequently. If we provide a `From<PackageUrl>`  implementation, that will expose the `PackageUrl` type in the public API, and require an incompatible SemVer change to this crate every time the SemVer of `PackageUrl` is bumped.

Could you provide a `FromStr` implementation instead?

2023-10-29 11:41 UTC, Shnatsel approved these changes

2023-10-29 11:42 UTC, Shnatsel commented
Thanks! Just needs a signoff with `git rebase HEAD~5 --signoff`  and then `git push --force`, and I can merge!

2023-10-29 17:00 UTC, merged