Include the target platform in the SBOM filename
CycloneDX/cyclonedx-rust-cargo pull request #535
Opened 2023-11-03 02:21 UTC by Shnatsel

And provide a `--no-target-suffix` flag to let people opt out.

2023-11-03 07:54 UTC, lfrancke requested changes

2023-11-03 07:54 UTC, lfrancke commented on cargo-cyclonedx/src/cli.rs
> +    pub no_target_suffix: bool,
Personally I think this should be off by default.

2023-11-03 07:54 UTC, lfrancke commented on cargo-cyclonedx/src/cli.rs
> +                    cdx_extension: cdx_extension.unwrap_or_default(),
This comment doesn't concern this line in particular but in https://cyclonedx.org/specification/overview/#recognized-file-patterns it is outlined how a valid CycloneDX file is called and this PR violates that.

If it's not `bom.xml` anymore, it should be `bom_x86_64-unknown-linux-gnu.cdx.xml`

2023-11-03 07:55 UTC, lfrancke commented
To summarize my review:

- I see that people might want this, I don't think I'll need it but I'm not opposed
- I'd like to make this opt-in rather than opt-out
- We should stay compatible with the recognized file patterns which would imply to use the cdx suffix if target is included

2023-11-09 22:15 UTC, Shnatsel commented
I believe I have addressed the review feedback, PTAL.

2023-11-12 20:58 UTC, lfrancke approved these changes

2023-11-12 21:55 UTC, merged